In [58]:
import requests
import urllib.parse

In [59]:
url = "https://data.boston.gov/api/3/action/datastore_search_sql"

In [60]:
sql = '''
SELECT
  "DISTRICT",
  "OCCURRED_ON_DATE",
  "SHOOTING",
  "OFFENSE_DESCRIPTION",
  "HOUR"
FROM "b973d8cb-eeb2-4e7e-99da-c92938efc9c0"
WHERE CAST("SHOOTING" AS INT) = 1
'''

In [61]:
# Build URL
final_url = url + "?sql=" + urllib.parse.quote(sql)


# Request data
rows = requests.get(final_url).json()

# Extract records
shootings = rows['result']['records']

In [62]:
print("Total records:", len(shootings))
print("First record:", shootings[0])

Total records: 1735
First record: {'DISTRICT': 'B3', 'OCCURRED_ON_DATE': '2023-02-18 21:43:00+00', 'SHOOTING': '1', 'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER', 'HOUR': '21'}

In [63]:
for s in shootings[:10]:
    print(s["DISTRICT"])

B3
D4
D4
B3
B2
C11
B2
B2
C11
B3

In [64]:
import pandas as pd

In [65]:
# Convert to DataFrame
df = pd.DataFrame(shootings)

In [66]:
# Clean data
df = df[df['DISTRICT'].notna()]
df['HOUR'] = df['HOUR'].astype(int)

In [67]:
#  Chart 1 data
district_counts = df.groupby('DISTRICT').size().reset_index(name='count')

In [68]:
# Chart 2 data
hour_counts = df.groupby('HOUR').size().reset_index(name='count')

In [69]:
# Show results
display(district_counts)
display(hour_counts)

    DISTRICT  count
0         A1     40
1        A15     16
2         A7     29
3         B2    417
4         B3    421
5        C11    335
6         C6     61
7        D14     40
8         D4     86
9        E13    119
10       E18    110
11        E5     57
12  External      3

    HOUR  count
0      0    186
1      1    142
2      2    110
3      3     85
4      4     57
5      5     45
6      6     32
7      7     25
8      8     12
9      9     24
10    10     21
11    11     32
12    12     31
13    13     18
14    14     32
15    15     44
16    16     44
17    17     66
18    18     66
19    19     87
20    20    123
21    21    146
22    22    150
23    23    156

In [70]:
# Save CSV files
district_counts.to_csv("district.csv", index=False)
hour_counts.to_csv("hour.csv", index=False)

In [71]:
# Bonus dataset for linking charts
district_hour = df.groupby(['DISTRICT','HOUR']).size().reset_index(name='count')
district_hour.to_csv("district_hour.csv", index=False)

In [74]:
print("Files saved!")

Files saved!

In [76]:
from google.colab import files

files.download("district.csv")
files.download("hour.csv")
files.download("district_hour.csv")